name: challemge1
on: 
  workflow_dispatch
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: |
        date
        pwd
        ls -l
  job2:
    name: job2
    runs-on: ubuntu-latest
    steps:
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: step1
      run: python --version
    - name: step2 setup pandas
      run: |
        pip install pandas
        pip --version 
    - name: step3 create artefact
      run: |
        touch artefact.py
        echo "# This is my python artifact" > artifact.py 
        python artefact.py